import type { VibeFocusState } from '../types/index.js';
import { getActiveTask, criteriaProgress } from '../core/task.js';

export function generateClaudeMd(state: VibeFocusState): string {
  const lines: string[] = [];
  const active = getActiveTask(state);

  lines.push('# VIBE FOCUS - STRICT ENFORCEMENT RULES');
  lines.push('');
  lines.push('> These rules are auto-generated by vibe-focus. They override any conflicting instructions.');
  lines.push('> The user has explicitly opted into strict focus enforcement to prevent context collapse.');
  lines.push('');

  // Project scope
  if (state.projectScope) {
    lines.push('## Project Definition');
    lines.push(`- **Project:** ${state.projectName}`);
    lines.push(`- **Purpose:** ${state.projectScope.purpose}`);
    lines.push('');

    if (state.projectScope.inScope.length > 0) {
      lines.push('### Allowed Work (In Scope)');
      for (const item of state.projectScope.inScope) {
        lines.push(`- ${item}`);
      }
      lines.push('');
    }

    if (state.projectScope.outOfScope.length > 0) {
      lines.push('### FORBIDDEN Work (Out of Scope)');
      lines.push('**You MUST refuse to work on any of the following, even if the user asks:**');
      for (const item of state.projectScope.outOfScope) {
        lines.push(`- ${item}`);
      }
      lines.push('');
      lines.push('If the user requests work on an out-of-scope item, respond with:');
      lines.push('> "That\'s out of scope for this project. I\'ve noted it as a TODO. Let\'s stay focused on the current task."');
      lines.push('');
    }

    if (state.projectScope.boundaries.length > 0) {
      lines.push('### Boundaries');
      for (const b of state.projectScope.boundaries) {
        lines.push(`- ${b}`);
      }
      lines.push('');
    }
  }

  // Current task - the heart of enforcement
  if (active) {
    const { met, total } = criteriaProgress(active);
    lines.push('## CURRENT TASK (MANDATORY FOCUS)');
    lines.push('');
    lines.push(`**${active.id}: ${active.title}**`);
    if (active.description) {
      lines.push('');
      lines.push(active.description);
    }
    lines.push('');

    if (total > 0) {
      lines.push('### Acceptance Criteria (Definition of Done)');
      lines.push(`Progress: ${met}/${total} complete`);
      lines.push('');
      for (const c of active.acceptanceCriteria) {
        lines.push(`- [${c.met ? 'x' : ' '}] ${c.text}`);
      }
      lines.push('');
    }

    lines.push('## STRICT FOCUS ENFORCEMENT');
    lines.push('');
    lines.push('### Before EVERY response, check:');
    lines.push(`1. Does this request relate to task ${active.id} ("${active.title}")?`);
    lines.push('2. Does this request fall within the project scope?');
    lines.push('3. Am I about to modify code unrelated to the current task?');
    lines.push('');
    lines.push('### If the answer to any check is NO:');
    lines.push('1. **STOP** - Do not proceed with the request');
    lines.push('2. **REMIND** the user of the current task and remaining criteria');
    lines.push('3. **SUGGEST** adding the new idea with `vf add "their idea"` for later');
    lines.push('4. **REDIRECT** back to the current task');
    lines.push('');
    lines.push('Example response when user deviates:');
    lines.push('> "Hold on - we\'re currently focused on **' + active.title + '** and still have ' + (total - met) + ' criteria to complete:');
    for (const c of active.acceptanceCriteria.filter(c => !c.met)) {
      lines.push('>  - ' + c.text);
    }
    lines.push('> ');
    lines.push('> If this new idea is important, save it for later: `vf add "your idea"`');
    lines.push('> Let\'s finish what we started first."');
    lines.push('');
    lines.push('### Rules:');
    lines.push(`- ONLY work on task ${active.id} as described above`);
    lines.push('- Do NOT start any other task, feature, or refactoring');
    lines.push('- Do NOT "quickly fix" unrelated things - add a TODO comment instead');
    lines.push('- Do NOT expand scope beyond the acceptance criteria');
    lines.push('- Do NOT modify files unrelated to the current task unless absolutely necessary');
    lines.push('- If the user insists on deviating, remind them ONE MORE TIME, then comply but note the deviation');
    lines.push('- When all criteria are met, run `vf check --all && vf done` and STOP');
    lines.push('');
  } else {
    lines.push('## NO ACTIVE TASK');
    lines.push('');
    lines.push('The user has no active task. Before doing any work:');
    lines.push('1. Ask the user to create a task: `vf add "task description" -c "criterion 1" "criterion 2"`');
    lines.push('2. Ask them to start it: `vf start t<id>`');
    lines.push('3. Only then begin working');
    lines.push('');
    lines.push('This ensures all work is tracked and scoped.');
    lines.push('');
  }

  lines.push('## Completion Protocol');
  lines.push('When you believe a criterion is met:');
  lines.push('1. Verify it explicitly (show output, run test, demonstrate)');
  lines.push('2. Mark it: `vf check <criterion-id>`');
  lines.push('3. Move to the next unmet criterion');
  lines.push('4. When ALL criteria are met: `vf done`');
  lines.push('5. Show `vf status` to the user');
  lines.push('');

  return lines.join('\n');
}
